# These are supported funding model platforms

github:[jobajuba, yostudent]
patreon: yostudent
community_bridge: https://img.shields.io/github/sponsors/yostudent?color=green&label=Become%20a%20sponsor&style=for-the-badge\
custom: ['https://www.patreon.com/yostudent', 'https://yumpie.app/']
